/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    Card: typeof import('primevue/card')['default']
    CardTitle: typeof import('./src/components/CardTitle.vue')['default']
    Chart: typeof import('primevue/chart')['default']
    FieldsetCard: typeof import('./src/components/FieldsetCard.vue')['default']
    Fluid: typeof import('primevue/fluid')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    ProcessFlowChart: typeof import('./src/components/ProcessFlowChart.vue')['default']
    ProcessFlowTemplating: typeof import('./src/components/ProcessFlowTemplating.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timeline: typeof import('primevue/timeline')['default']
  }
}
